/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yahoo.search;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.text.Document;
import javax.swing.text.html.HTMLEditorKit;

/**
 *
 * @author M Awais
 */
public class YahooSearchJFrame extends javax.swing.JFrame {

    /**
     * Creates new form YahooSearchJFrame
     */
    private HTMLEditorKit kit;
    public YahooSearchJFrame() {
        initComponents();
        kit = new HTMLEditorKit();
        jEditorPane.setEditorKit(kit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SearchjTextArea = new javax.swing.JTextArea();
        SearchjButton = new javax.swing.JButton();
        SearchingjProgressBar = new javax.swing.JProgressBar();
        SearchingjLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane = new javax.swing.JEditorPane();
        ChoseFolderjButton = new javax.swing.JButton();
        SearchingjLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yahoo Searcher");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel1.setText("Enter Search Srtings Here");

        SearchjTextArea.setColumns(20);
        SearchjTextArea.setRows(5);
        SearchjTextArea.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204)));
        jScrollPane1.setViewportView(SearchjTextArea);

        SearchjButton.setBackground(new java.awt.Color(0, 255, 0));
        SearchjButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchjButton.setForeground(new java.awt.Color(204, 0, 204));
        SearchjButton.setText("Search");
        SearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchjButtonActionPerformed(evt);
            }
        });

        SearchingjLabel.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        SearchingjLabel.setText("Searching Status");

        jScrollPane2.setViewportView(jEditorPane);

        ChoseFolderjButton.setBackground(new java.awt.Color(255, 255, 204));
        ChoseFolderjButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ChoseFolderjButton.setForeground(new java.awt.Color(51, 0, 51));
        ChoseFolderjButton.setText("Chose Folder");
        ChoseFolderjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChoseFolderjButtonActionPerformed(evt);
            }
        });

        SearchingjLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        SearchingjLabel1.setText("Must chose folder for file first else it will show error");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ChoseFolderjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addComponent(SearchjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchingjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SearchingjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(SearchingjProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchingjLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchingjProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(SearchjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchingjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ChoseFolderjButton)
                        .addGap(38, 38, 38))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //private String htmlString; 
    
    
    private String plainText;
    private String htmlText;
    private YahooSearch yahSear;
    private void SearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchjButtonActionPerformed
       Date date = new Date();
       String urls=SearchjTextArea.getText();
       if(urls.length()==0)
       {
        JOptionPane.showMessageDialog(null, "Enter any text please!", "Text Not Entered!", JOptionPane.ERROR_MESSAGE); 
        return;
       }
           
       String csvFile="";
       if(path!=null)
       {
           csvFile =path+"\\"+date.getTime()+".csv";
       }else
       {
           JOptionPane.showMessageDialog(null, "You have not chose any folder\nwhere file will save.Please Select any folder!", "Folder Not Chosen!", JOptionPane.ERROR_MESSAGE); 
           return;
       }
       
       JOptionPane.showMessageDialog(null,"Searching Started!\nWait Until Next Not Message Show.","Searching...",  JOptionPane.INFORMATION_MESSAGE);
        FileWriter writer = null;
        try
        {
            writer = new FileWriter(csvFile);
            writer.append("Keywords,\"Results\"\n");
        }catch(IOException e)
        {
            JOptionPane.showMessageDialog(null, e, "File Error", JOptionPane.ERROR_MESSAGE);    
        }
        CsvUtils csvUtils=new CsvUtils();
        yahSear=new YahooSearch();
        String[] splitStr = urls.split("\\n");
        int size=splitStr.length,i=1;
        for(String singleStr: splitStr)
        {
            SearchingjProgressBar.setValue((i/size)*100);
            try{
                htmlText=yahSear.search(singleStr);
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, "Internet Connrction Error!", "Connection Fail", JOptionPane.ERROR_MESSAGE);
                return;
            }
           try { 
               writer.append(singleStr+",\""+csvUtils.writeLine(execuator(htmlText))+"\"\n");
              
           } catch (IOException e) {
               JOptionPane.showMessageDialog(null, e, "File writing Error", JOptionPane.ERROR_MESSAGE);    
           }
            i++;
            
        }
        try{
            writer.flush();
            writer.close();
        } catch (IOException e) {
               JOptionPane.showMessageDialog(null, e, "File closing Error", JOptionPane.ERROR_MESSAGE);    
           }
        
        JOptionPane.showMessageDialog(null,"Searching Completed & File Created","Done",  JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_SearchjButtonActionPerformed
    private String path;
    private void ChoseFolderjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChoseFolderjButtonActionPerformed
        JFileChooser chooser=new JFileChooser();
        chooser.setDialogTitle("Chose Folder To save Search Result");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
       // chooser.setAcceptAllFileFilterUsed(false);
        chooser.showOpenDialog(null);
     
            path=chooser.getSelectedFile().getPath();
       
    }//GEN-LAST:event_ChoseFolderjButtonActionPerformed
    
    
    private String execuator(String htmlString){
        Document doc = kit.createDefaultDocument();
              jEditorPane.setDocument(doc);
              jEditorPane.setText(htmlString);
              jEditorPane.selectAll();
              plainText=jEditorPane.getSelectedText();
              return plainText;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YahooSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YahooSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YahooSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YahooSearchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YahooSearchJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChoseFolderjButton;
    private javax.swing.JLabel SearchingjLabel;
    private javax.swing.JLabel SearchingjLabel1;
    private javax.swing.JProgressBar SearchingjProgressBar;
    private javax.swing.JButton SearchjButton;
    private javax.swing.JTextArea SearchjTextArea;
    private javax.swing.JEditorPane jEditorPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
